### ISSUE TITLE
vim 8.2, vim-go, vim-bazel, errcheck, & rules_go

### ISSUE THREAD

**Issue by BooneJS** [bazelbuild/vim-bazel#14]
Hi,

I'm using vim 8.2, vim-go (latest), errcheck (latest), and vim-bazel (latest) on macOS Catalina. I'm using go_proto_library() to compile a protobuf, but vim-go flags my import as being not found despite Bazel successfully compiling it.

It's not that big of a deal because it's a warning I can ignore, but I was wondering if there's something quick and easy I can do to make it go away.

Thanks!

**Comment by malcolmr** [comment]
This seems like a bug for vim-go, not vim-bazel? (Presumably you could compile the protobuf with command-line Bazel as well, and still see the same problem.)

In particular, perhaps this is https://github.com/fatih/vim-go/issues/1328?
